// src/themes/Console/components/BlockCursor/index.tsx
import { useEffect, useRef, useState } from "react";
import style from "./style.module.css";
import Classes from "@/util/Classes.ts";
import { XY } from "@/util/metricsTypes.ts";

export type BlockCursorType = "block" | "invert";
export type GridSize = { x: number; y: number };

const onCursorMove = (e: MouseEvent, parent: Element, setPosition: (xy: XY) => void, gridSize: XY) => {
	const parentRect = parent.getBoundingClientRect();

	const realPos = {
		x: e.clientX - parentRect.left,
		y: e.clientY - parentRect.top,
	};

	const gridPosition = {
		x: Math.floor(realPos.x / gridSize.x) * gridSize.x,
		y: Math.floor(realPos.y / gridSize.y) * gridSize.y,
	};

	setPosition(gridPosition);
};

type BlockCursorProps = { gridSize: GridSize; cursor?: string; type?: BlockCursorType; colors?: [string, string] };
const BlockCursor = ({ type = "invert", colors = ["#fff", "#000"], gridSize }: BlockCursorProps) => {
	const [position, setPosition] = useState({ x: 0, y: 0 });
	const ref = useRef(null);
	useEffect(() => {
		if (!ref.current) return;

		const element = ref.current as HTMLElement;
		const parent = element.offsetParent ?? document.body;

		const trackCursor = (e: MouseEvent) => {
			const bodyClasses = new Classes(document.body.className);
			document.body.className = bodyClasses.push(style.cursorHidden).all();
			onCursorMove(e, parent, setPosition, gridSize);
		};

		const showPointer = () => {
			const bodyClasses = new Classes(document.body.className);
			document.body.className = bodyClasses.remove(style.cursorHidden).all();
		};

		element.style.setProperty(`--grid-x`, `${gridSize.x}px`);
		element.style.setProperty(`--grid-y`, `${gridSize.y}px`);

		parent.addEventListener("mousemove", trackCursor as EventListener);

		return () => {
			parent.removeEventListener("mousemove", trackCursor as EventListener);
			showPointer();
		};
	}, [ref.current, setPosition, gridSize]);

	const styles = {
		left: position.x,
		top: position.y,
		...(type === "invert"
			? {}
			: {
					color: colors[0],
					backgroundColor: colors[1],
				}),
	};

	return (
		<div ref={ref} style={styles} className={[style.blockCursor, type === "invert" ? style.invert : ""].join(" ")}>
			{" "}
		</div>
	);
};

export default BlockCursor;

// src/themes/Console/components/BlockCursor/BlockCursor.vue
<script setup lang="ts">
import {computed, onMounted, onUnmounted, ref, type Ref} from "vue";
import type XY from "@t/XY.ts";
import {charGrid} from "../../constants.ts";

export type BlockCursorType = "block" | "invert";
export type GridSize = { x: number; y: number };

type Props = {
	elementRef?: Ref<HTMLElement>;
	type?: BlockCursorType;
	colors?: [string, string];
	gridSize?: GridSize
};

const props = withDefaults(defineProps<Props>(), {
	elementRef: () => ref(document.body as HTMLElement),
	type: "invert",
	colors: () => ["#fff", "#000"],
	gridSize: () => ({...charGrid}),
});

const cursorRef = ref<HTMLElement>();
const positionRef = ref<XY>({x: 0, y: 0});

const onCursorMove = (e: MouseEvent) => {
	if (!cursorRef.value) return;

	const parent = cursorRef.value.offsetParent ?? document.body;
	const parentRect = parent.getBoundingClientRect();
	const realPos = {
		x: e.clientX - parentRect.left,
		y: e.clientY - parentRect.top,
	};

	const gridPosition = {
		x: Math.floor(realPos.x / props.gridSize.x) * props.gridSize.x,
		y: Math.floor(realPos.y / props.gridSize.y) * props.gridSize.y,
	};

	Object.assign(positionRef.value, gridPosition);
};

const styles = computed(() => ({
	left: `${positionRef.value.x}px`,
	top: `${positionRef.value.y}px`,
	width: `${props.gridSize.x}px`,
	height: `${props.gridSize.y}px`,
	color: props.type === "invert" ? "#fff" : "inherit",
}))

onMounted(() => {
	props.elementRef.value.addEventListener("mousemove", onCursorMove);
	props.elementRef.value.classList.add("winman-cursor-hide");
});

onUnmounted(() => {
	if (props.elementRef.value) props.elementRef.value.classList.remove("winman-cursor-hide");
	if (!cursorRef.value) return;
});
</script>

<template>
	<Teleport v-if="elementRef.value" :to="elementRef.value">
		{{styles}}
		<div ref="cursorRef" :class="['cursor', {invert: type === 'invert'}]" :style="styles" />
	</Teleport>
</template>

<style lang="scss" scoped>
.cursor {
	position: absolute;
	font-family: "DOS437Unicode", monospace;
	background-color: #fff;

	pointer-events: none;
	z-index: 125000;
}
.cursor.invert {
	background-color: transparent;
	backdrop-filter: invert(100%);
}
</style>

<style>
.winman-cursor-hide, .winman-cursor-hide * {
	cursor: none;
}
</style>
